# ============================================================
# Create Table 3 (Model 2) from a simulation summary CSV.
#
# Usage from the repository root:
#   Rscript make_table3.R
#   Rscript make_table3.R INPUT_CSV OUTPUT_TEX
# ============================================================

command_args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", command_args, value = TRUE)

if (length(file_arg) > 0) {
  script_file <- normalizePath(sub("^--file=", "", file_arg[1]))
} else {
  script_file <- tryCatch(
    normalizePath(sys.frame(1)$ofile),
    error = function(e) NA_character_
  )
}

if (is.na(script_file)) {
  stop("Cannot locate this script. Run it with Rscript from the repository.")
}

script_dir <- dirname(script_file)
project_dir <- script_dir
args <- commandArgs(trailingOnly = TRUE)

latest_file <- file.path(
  project_dir,
  "results",
  "latest",
  "simulation_summary_long.csv"
)

if (length(args) >= 1) {
  input_file <- normalizePath(args[1], mustWork = TRUE)
} else {
  input_file <- latest_file
}

output_file <- if (length(args) >= 2) {
  args[2]
} else {
  file.path(project_dir, "tables", "table3_model2.tex")
}

method_spec <- data.frame(
  Estimator = c(
    "PO-only",
    "PO_group_specific",
    "PO_group_specific_quantileCensoring",
    "AH-Cox-only",
    "Stacked-GMM-AH-Cox",
    "Stacked-GMM-POGS-AH-Cox",
    "Stacked-GMM-POGS-quantileCensoring-AH-Cox"
  ),
  Label = c(
    "PO",
    "PO-GS",
    "PO-GS-QC",
    "AH-Cox",
    "Stacked GMM",
    "GMM-POGS",
    "GMM-POGS-QC"
  ),
  stringsAsFactors = FALSE
)

censoring_spec <- data.frame(
  Censoring = c(
    "none",
    "independent",
    "group_specific",
    "covariate_dependent"
  ),
  Label = c(
    "(a) No censoring",
    "(b) Independent",
    "(c) Group-specific",
    "(d) Covariate-dep."
  ),
  stringsAsFactors = FALSE
)

parameter_order <- c("Intercept", "Age", "LogBili", "Albumin")

format_true <- function(x) sprintf("%.3f", x)
format_rb <- function(x) sprintf("%.1f", 100 * x)
format_three <- function(x) sprintf("%.3f", x)

build_table <- function(dat) {
  required_columns <- c(
    "Model",
    "Censoring",
    "Estimator",
    "Parameter",
    "nsim",
    "True",
    "Rel_Bias",
    "Empirical_SD",
    "Mean_SE",
    "Coverage"
  )
  missing_columns <- setdiff(required_columns, names(dat))
  if (length(missing_columns) > 0) {
    stop("Missing required columns: ", paste(missing_columns, collapse = ", "))
  }

  dat <- dat[
    dat$Model == "Model 2" &
      dat$Estimator %in% method_spec$Estimator,
    ,
    drop = FALSE
  ]

  expected_keys <- expand.grid(
    Censoring = censoring_spec$Censoring,
    Estimator = method_spec$Estimator,
    Parameter = parameter_order,
    stringsAsFactors = FALSE
  )
  observed_keys <- dat[, c("Censoring", "Estimator", "Parameter")]
  key_counts <- table(
    interaction(observed_keys, drop = TRUE, lex.order = TRUE)
  )

  if (nrow(dat) != nrow(expected_keys) || any(key_counts != 1)) {
    stop(
      "Model 2 does not contain exactly one row for every ",
      "censoring-method-parameter combination."
    )
  }

  numeric_columns <- c(
    "True",
    "Rel_Bias",
    "Empirical_SD",
    "Mean_SE",
    "Coverage"
  )
  if (any(!is.finite(as.matrix(dat[, numeric_columns])))) {
    stop("Model 2 contains non-finite reported statistics.")
  }

  nsim_values <- unique(dat$nsim)
  if (length(nsim_values) != 1 || !is.finite(nsim_values)) {
    stop("Model 2 must contain one finite nsim value.")
  }
  nsim_value <- as.integer(nsim_values)

  method_header <- paste(
    vapply(
      method_spec$Label,
      function(label) {
        paste0("\\multicolumn{4}{c}{\\textbf{", label, "}}")
      },
      character(1)
    ),
    collapse = " & "
  )

  lines <- c(
    "% Generated by make_table3.R",
    paste0("% Source: ", basename(input_file)),
    "\\begin{landscape}",
    "\\begin{table}[htbp]",
    "\\small",
    "\\centering",
    paste0(
      "\\caption{Simulation results for Model~2 ",
      "(Weibull shape $\\kappa = 2$), ",
      "$n = 300$, $B = ", nsim_value, "$ replications, $\\tau = 7$. ",
      "Column definitions as in Table~\\ref{tab:model1}.}"
    ),
    "\\label{tab:model2}",
    "\\setlength{\\tabcolsep}{3.2pt}",
    "\\resizebox{\\linewidth}{!}{%",
    "\\begin{tabular}{lll rrrr rrrr rrrr rrrr rrrr rrrr rrrr}",
    "\\toprule",
    paste0("& & & ", method_header, " \\\\"),
    paste0(
      "\\cmidrule(lr){4-7}\\cmidrule(lr){8-11}",
      "\\cmidrule(lr){12-15}\\cmidrule(lr){16-19}",
      "\\cmidrule(lr){20-23}\\cmidrule(lr){24-27}",
      "\\cmidrule(lr){28-31}"
    ),
    paste0(
      "\\textbf{Censoring} & \\textbf{Parameter} & \\textbf{True} & ",
      paste(rep("RB & ESD & MSE & CP", 7), collapse = " & "),
      " \\\\"
    ),
    "\\midrule"
  )

  for (censor_index in seq_len(nrow(censoring_spec))) {
    censoring_name <- censoring_spec$Censoring[censor_index]

    for (parameter_index in seq_along(parameter_order)) {
      parameter_name <- parameter_order[parameter_index]
      first_method_row <- dat[
        dat$Censoring == censoring_name &
          dat$Estimator == method_spec$Estimator[1] &
          dat$Parameter == parameter_name,
        ,
        drop = FALSE
      ]

      fields <- c(
        if (parameter_index == 1) censoring_spec$Label[censor_index] else "",
        parameter_name,
        paste0("$", format_true(first_method_row$True), "$")
      )

      for (estimator_name in method_spec$Estimator) {
        row <- dat[
          dat$Censoring == censoring_name &
            dat$Estimator == estimator_name &
            dat$Parameter == parameter_name,
          ,
          drop = FALSE
        ]
        fields <- c(
          fields,
          paste0("$", format_rb(row$Rel_Bias), "$"),
          format_three(row$Empirical_SD),
          format_three(row$Mean_SE),
          format_three(row$Coverage)
        )
      }

      lines <- c(lines, paste0(paste(fields, collapse = " & "), " \\\\"))
    }

    if (censor_index < nrow(censoring_spec)) {
      lines <- c(lines, "\\midrule")
    }
  }

  c(
    lines,
    "\\bottomrule",
    "\\end{tabular}",
    "}",
    "\\end{table}",
    "\\end{landscape}"
  )
}

if (!file.exists(input_file)) {
  stop(
    "Cannot find simulation summary: ", input_file,
    "\nRun main.R or provide an input path."
  )
}

simulation_summary <- read.csv(
  input_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)
table_lines <- build_table(simulation_summary)

dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)
writeLines(table_lines, output_file, useBytes = TRUE)

cat("Table 3 written to:\n", normalizePath(output_file), "\n", sep = "")
